---
title: "t Lung CellChat Individual Object Creation for T Cells and ECs and all figures"
output: html_notebook
---



```{r}
library(NMF)
library(uwot)
library(ggalluvial)
library(CellChat)
library(patchwork)
options(stringsAsFactors = FALSE)
library(Seurat)
library(SeuratWrappers)
library(future)
library(igraph)
```

```{r}
tLung_lung_carcinoma_seurat_object <- readRDS("/Users/soumyasharma/Desktop/Studies/MS_Systems_Biology/Project_2/Seurat_data_center/EC_T_Cells_Seurat_Objects/tLung_lung_carcinoma_seurat_T_EC_cells.rds")
```


```{r}
cellchat <- readRDS("/Users/soumyasharma/Desktop/Studies/MS_Systems_Biology/Project_2/CellChat/CellChat_T_ECs_Final/Data/CellChat_objects/tLung_T_EC_cells_CellChat_Object.rds")
```


```{r}
t_lung_T_EC_cells_under_investigation <- tLung_lung_carcinoma_seurat_object@meta.data$Cell_subtype

t_lung_T_EC_cells_barcode <- tLung_lung_carcinoma_seurat_object@meta.data$Index

t_lung_T_EC_cells_under_investigation <- tLung_lung_carcinoma_seurat_object[,t_lung_T_EC_cells_barcode]

data.input <- GetAssayData(t_lung_T_EC_cells_under_investigation, assay = "RNA", slot = "data") # normalized data matrix
labels <- t_lung_T_EC_cells_under_investigation@meta.data$Cell_subtype
meta <- data.frame(group = labels, row.names = names(labels)) # create a dataframe of the cell labels

cellchat <- createCellChat(object = t_lung_T_EC_cells_under_investigation,
                           group.by = 'Cell_subtype')

groupSize <- as.numeric(table(cellchat@idents)) # number of cells in each cell group
```


```{r}
levels(cellchat@idents) 

CellChatDB <- CellChatDB.human # use CellChatDB.mouse if running on mouse data
showDatabaseCategory(CellChatDB)

# Show the structure of the database
dplyr::glimpse(CellChatDB$interaction)

# use all CellChatDB for cell-cell communication analysis
CellChatDB.use <- CellChatDB # simply use the default CellChatDB

# set the used database in the object
cellchat@DB <- CellChatDB.use

# subset the expression data of signaling genes for saving computation cost
cellchat <- subsetData(cellchat) # This step is necessary even if using the whole database
future::plan("multiprocess") # do parallel

cellchat <- identifyOverExpressedGenes(cellchat)

cellchat <- identifyOverExpressedInteractions(cellchat)


cellchat <- computeCommunProb(cellchat)
# Filter out the cell-cell communication if there are only few number of cells in certain cell groups
cellchat <- filterCommunication(cellchat, min.cells = 10)

cellchat <- computeCommunProbPathway(cellchat)

cellchat <- aggregateNet(cellchat)

cell_levels <- as.data.frame(levels(cellchat@idents)) # show factor levels of the cell labels

group_size <- as.data.frame(groupSize)

group_size

cell_levels

```


```{r}

groupSize <- as.numeric(table(cellchat@idents))
par(mfrow = c(1,1), xpd=TRUE)
netVisual_circle(cellchat@net$count, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Number of interactions")
netVisual_circle(cellchat@net$weight, vertex.weight = groupSize, weight.scale = T, label.edge= F, title.name = "Interaction weights/strength")

mat <- cellchat@net$weight
par(mfrow = c(1,1), xpd=TRUE)
for (i in 1:nrow(mat)) {
  mat2 <- matrix(0, nrow = nrow(mat), ncol = ncol(mat), dimnames = dimnames(mat))
  mat2[i, ] <- mat[i, ]
  netVisual_circle(mat2, vertex.weight = groupSize, weight.scale = T, edge.weight.max = max(mat), title.name = rownames(mat)[i])
}

```



```{r}
#All the signaling pathways showing significant communications can be accessed by cellchat@netP$pathways

significant_communication_pathways <- cellchat@netP$pathways

significant_communication_pathways <- as.data.frame(significant_communication_pathways)

significant_communication_pathways

write.csv(significant_communication_pathways,"../tlung_T_EC_cells_significant_communication_pathways.csv", row.names = TRUE)
```


```{r}
df.net <- subsetCommunication(cellchat)

#slot.name = "netP" to access the the inferred communications at the level of signaling pathways
df.net <- subsetCommunication(cellchat, slot.name = "netP")

#returns a data frame consisting of all the inferred cell-cell communications at the level of ligands/receptors.
df.net.LR <- subsetCommunication(cellchat)
```

```{r}
#gives the inferred cell-cell communications mediated by signaling WNT and TGFb.
#df.net.specific.LR <- subsetCommunication(cellchat, signaling = c("CCL", "MK"))
```


```{r}
df.net.by_cell <- subsetCommunication(cellchat) # sources.use = c(1,2), targets.use = c(1,2))
```



YOU CAN DO A PATHWAY SPECIFIC ANALYSIS FROM HERE. THE CODES THAT HAVE BEEN COMMENTED OUT CORRESPOND 


```{r}
#pathways.show <- c("MHC-I") 
# Hierarchy plot
# Here we define `vertex.receive` so that the left portion of the hierarchy plot shows signaling to fibroblast and the right portion shows signaling to immune cells 
#vertex.receiver = seq(1,4) # a numeric vector. 
#netVisual_aggregate(cellchat, signaling = pathways.show,  vertex.receiver = vertex.receiver)
```



```{r}
# Circle plot
#par(mfrow=c(1,1))
#netVisual_aggregate(cellchat, signaling = pathways.show, layout = "circle")
```


```{r}
# Chord diagram
#par(mfrow=c(2,3))
#netVisual_aggregate(cellchat, signaling = pathways.show, layout = "chord")
#> Note: The first link end is drawn out of sector 'Inflam. FIB'.
```


```{r}
# Heatmap
#par(mfrow=c(1,1))
#netVisual_heatmap(cellchat, signaling = pathways.show, color.heatmap = "Reds")
#> Do heatmap based on a single object
```


```{r}
#netAnalysis_contribution(cellchat, signaling = pathways.show)
```


```{r}
#pairLR.MHCI <- extractEnrichedLR(cellchat, signaling = pathways.show, geneLR.return = FALSE)
#LR.show <- pairLR.MHCI[1,] # show one ligand-receptor pair
# Hierarchy plot
#vertex.receiver = seq(1,4) # a numeric vector
#netVisual_individual(cellchat, signaling = pathways.show,  pairLR.use = LR.show, vertex.receiver = vertex.receiver)
```


```{r}
# Chord diagram
#group.cellType <- c(rep("FIB", 4), rep("DC", 4), rep("TC", 4)) # grouping cell clusters into fibroblast, DC and TC cells
#names(group.cellType) <- levels(cellchat@idents)
#netVisual_chord_cell(cellchat, signaling = pathways.show, group = group.cellType, title.name = paste0(pathways.show, " signaling network"))
#> Plot the aggregated cell-cell communication network at the signaling pathway level
#> Note: The first link end is drawn out of sector 'Inflam. FIB'.
```


```{r}
# Circle plot
#netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "circle")
```


```{r}
#> [[1]]
# Chord diagram
#netVisual_individual(cellchat, signaling = pathways.show, pairLR.use = LR.show, layout = "chord")
#> Note: The first link end is drawn out of sector 'Inflam. FIB'.
```



```{r}
# Access all the signaling pathways showing significant communications
pathways.show.all <- cellchat@netP$pathways
# check the order of cell identity to set suitable vertex.receiver
levels(cellchat@idents)
vertex.receiver = seq(15,3)
for (i in 1:length(pathways.show.all)) {
  # Visualize communication network associated with both signaling pathway and individual L-R pairs
  netVisual(cellchat, signaling = pathways.show.all[i], vertex.receiver = vertex.receiver, layout = "hierarchy")
  # Compute and visualize the contribution of each ligand-receptor pair to the overall signaling pathway
  gg <- netAnalysis_contribution(cellchat, signaling = pathways.show.all[i])
  ggsave(filename=paste0(pathways.show.all[i], "_L-R_contribution.pdf"), plot=gg, width = 3, height = 2, units = 'in', dpi = 300)
}
```


```{r}
# show all the significant interactions (L-R pairs) from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
#netVisual_bubble(cellchat, sources.use = 4, targets.use = c(5:11), remove.isolate = FALSE)
#> Comparing communications on a single object
```



```{r}
# show all the significant interactions (L-R pairs) associated with certain signaling pathways
#netVisual_bubble(cellchat, sources.use = 4, targets.use = c(5:11), signaling = c("CCL","CXCL"), remove.isolate = FALSE)
#> Comparing communications on a single object
```


```{r}
# show all the significant interactions (L-R pairs) based on user's input (defined by `pairLR.use`)
#pairLR.use <- extractEnrichedLR(cellchat, signaling = c("CCL","CXCL","FGF"))
#netVisual_bubble(cellchat, sources.use = c(3,4), targets.use = c(5:8), pairLR.use = pairLR.use, remove.isolate = TRUE)
#> Comparing communications on a single object
```



```{r}
# show all the significant interactions (L-R pairs) from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
# show all the interactions sending from Inflam.FIB
#netVisual_chord_gene(cellchat, sources.use = 4, targets.use = c(5:11), lab.cex = 0.5,legend.pos.y = 30)
```



```{r}
# show all the interactions received by Inflam.DC
#netVisual_chord_gene(cellchat, sources.use = c(1,2,3,4), targets.use = 8, legend.pos.x = 15)
```



```{r}
# show all the significant interactions (L-R pairs) associated with certain signaling pathways
#netVisual_chord_gene(cellchat, sources.use = c(1,2,3,4), targets.use = c(5:11), signaling = c("CCL","CXCL"),legend.pos.x = 8)
#> Note: The second link end is drawn out of sector 'CXCR4 '.
#> Note: The first link end is drawn out of sector 'CXCL12 '.
```



```{r}
# show all the significant signaling pathways from some cell groups (defined by 'sources.use') to other cell groups (defined by 'targets.use')
#netVisual_chord_gene(cellchat, sources.use = c(3), targets.use =c(3), slot.name = "netP", legend.pos.x = 1)
#> Note: The first link end is drawn out of sector 'CXCL '.
```



```{r}
#plotGeneExpression(cellchat, signaling = "CXCL")
```



```{r}
#plotGeneExpression(cellchat, signaling = "CXCL", enriched.only = FALSE)
```


```{r}
# Compute the network centrality scores

cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP") # the slot 'netP' means the inferred intercellular communication network of signaling pathways

# Visualize the computed centrality scores using heatmap, allowing ready identification of major signaling roles of cell groups

#netAnalysis_signalingRole_network(cellchat, signaling = pathways.show, width = 8, height = 2.5, font.size = 10)
```


```{r}
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
gg1 <- netAnalysis_signalingRole_scatter(cellchat)
#> Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
# Signaling role analysis on the cell-cell communication networks of interest
#gg2 <- netAnalysis_signalingRole_scatter(cellchat, signaling = c("CXCL", "CCL"))
#> Signaling role analysis on the cell-cell communication network from user's input
gg1 
```


```{r}
# Signaling role analysis on the aggregated cell-cell communication network from all signaling pathways
ht1 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "outgoing")
ht2 <- netAnalysis_signalingRole_heatmap(cellchat, pattern = "incoming")
ht1 + ht2
```


```{r}
# Signaling role analysis on the cell-cell communication networks of interest
#ht <- netAnalysis_signalingRole_heatmap(cellchat, signaling = c("CXCL", "CCL"))
```


```{r}
selectK(cellchat, pattern = "outgoing")
```


```{r}
nPatterns = 3
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "outgoing", k = nPatterns)

# river plot
netAnalysis_river(cellchat, pattern = "outgoing")
#> Please make sure you have load `library(ggalluvial)` when running this function

# dot plot
netAnalysis_dot(cellchat, pattern = "outgoing")

selectK(cellchat, pattern = "incoming")
```




```{r}
nPatterns = 3
cellchat <- identifyCommunicationPatterns(cellchat, pattern = "incoming", k = nPatterns)

# river plot
netAnalysis_river(cellchat, pattern = "incoming")
#> Please make sure you have load `library(ggalluvial)` when running this function

# dot plot
netAnalysis_dot(cellchat, pattern = "incoming")

```







```{r}
#Identify signaling groups based on their functional similarity

cellchat <- computeNetSimilarity(cellchat, type = "functional")
cellchat <- netEmbedding(cellchat, type = "functional")

#> Manifold learning of the signaling networks for a single dataset
cellchat <- netClustering(cellchat, type = "functional")
#> Classification learning of the signaling networks for a single dataset

# Visualization in 2D-space
netVisual_embedding(cellchat, type = "functional", label.size = 3.5)

netVisual_embeddingZoomIn(cellchat, type = "functional", nCol = 2)
```



```{r}
#Identify signaling groups based on structure similarity

cellchat <- computeNetSimilarity(cellchat, type = "structural")
cellchat <- netEmbedding(cellchat, type = "structural")

#> Manifold learning of the signaling networks for a single dataset
cellchat <- netClustering(cellchat, type = "structural")

# Visualization in 2D-space
netVisual_embedding(cellchat, type = "structural", label.size = 3.5)

#> Classification learning of the signaling networks for a single dataset
netVisual_embeddingZoomIn(cellchat, type = "structural", nCol = 2)

```



```{r}
saveRDS(cellchat, file = "tLung_T_EC_cells_CellChat_Object.rds")
```





























